FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y tmate openssh-client curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY vps-entrypoint.sh /vps-entrypoint.sh
RUN chmod +x /vps-entrypoint.sh

ENTRYPOINT ["/vps-entrypoint.sh"]
